name: Platformer Production Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        env:
          DOCKER_USER: docker.pkg.github.com/help-lk
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
        run: docker build . --file Dockerfile --tag
          ${DOCKER_USER}/${REPO_NAME}/help-web:${TAG}
      - name: Docker Push
        run: docker push ${DOCKER_USER}/${REPO_NAME}/help-web:${TAG}
        env:
          DOCKER_USER: docker.pkg.github.com/help-lk
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID}}
          project-id: ${{secrets.PROJECT_ID}}
          token: ${{secrets.TOKEN}}
          image-name: docker.pkg.github.com/help-lk/${{ github.event.repository.name
            }}/help-web
          tag: ${{github.sha}}
          container-id: 37964d01-c0f0-4dbd-af7e-2af3da43f0ac
