name: Platformer Generated e9c89676-4f14-4750-b1f8-3f478c3c52b1 Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: nj93/test
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag
          ${SERVICE_NAME}:${{steps.branch_name.outputs.SOURCE_TAG }}
      - name: Docker Push
        run: docker push $SERVICE_NAME:$TAG
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_e9c89676-4f14-4750-b1f8-3f478c3c52b1}}
          project-id: ${{secrets.PROJECT_ID_e9c89676-4f14-4750-b1f8-3f478c3c52b1}}
          token: ${{secrets.AUTOGENERATED_CICD_e9c89676-4f14-4750-b1f8-3f478c3c52b1}}
          image-name: $SERVICE_NAME
          tag: ${{steps.branch_name.outputs.SOURCE_TAG }}
          container-id: 206f61e6-88df-4703-bf78-0eab99da6169
