name: Platformer Generated test workflow 1 Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: chamodshehanka/test
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag
          ${SERVICE_NAME}:${{steps.branch_name.outputs.SOURCE_TAG }}
      - name: Docker Push
        run: docker push $SERVICE_NAME:$TAG
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_311a2d42-b43d-4ebf-b914-dec5bf8eead5}}
          project-id: ${{secrets.PROJECT_ID_311a2d42-b43d-4ebf-b914-dec5bf8eead5}}
          token: ${{secrets.AUTOGENERATED_CICD_311a2d42-b43d-4ebf-b914-dec5bf8eead5}}
          image-name: $SERVICE_NAME
          tag: ${{steps.branch_name.outputs.SOURCE_TAG }}
          container-id: e67d840a-40ad-4021-b5a7-f7bdb7d198f2
