name: Production Build
on:
  push:
    branches:
      - null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        env:
          DOCKER_USER: docker.pkg.github.com/${REPO_NAME}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
        run: docker build . --file Dockerfile --tag ${DOCKER_USER}/${REPO_NAME}:${TAG}
      - name: Docker Push
        run: docker push ${DOCKER_USER}/${DOCKER_REPO}:${TAG}
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_f2e0bef0_59ef_4269_8d2e_714743011c79}}
          project-id: ${{secrets.PROJECT_ID_f2e0bef0_59ef_4269_8d2e_714743011c79}}
          token: ${{secrets.AUTOGENERATED_CICD_f2e0bef0_59ef_4269_8d2e_714743011c79}}
          image-name: ${{secrets.DOCKER_USER}}/${{ github.event.repository.name }}
          tag: ${{github.sha}}
          container-id: "26"
